"""MGStage 探测间歇失败回归。

用户实测：`mgstage 200 609 ms 代理 探测失败: 搜索失败: 搜索页未解析到结果`，
且「有时候正常，但经常出现」。根因是站点侧软性拦截返回 200 非商品页，旧版一律
归为「未解析到结果」，用户无从判断是地域封锁、年龄确认页还是番号已下架。
这里锁定三类行为：探测番号指向真实收录的详情页、`_get_cookies` 带 adc
（探测与真实刮削一致）、「假 200」页面必须点名，以及命中年龄认证页时
自动选「はい（アダルトへ）」。
"""

import pytest
from parsel import Selector

from mdcx.crawlers.base import CrawlerException
from mdcx.crawlers.mgstage import MgstageCrawler
from mdcx.models.model_types import CrawlerInput

pytestmark = pytest.mark.asyncio


def _crawler_and_ctx(number: str = "259LUXU-1111", client=None):
    crawler = MgstageCrawler(client=client, browser=None)
    inp = CrawlerInput.empty()
    inp.number = number
    return crawler, crawler.new_context(inp)


AGE_GATE_HTML = """
<html><head><title>MGS動画(成人認証) - アダルト強調</title></head><body>
<div class="agecheck"><img src="/img/18.png" alt="18禁">
<h2>年齢認証</h2>
<p>ここから先は、アダルト商品を取り扱うアダルトサイトとなります。<br>
18歳未満の方のアクセスは固くお断り致します。</p>
<p>あなたは18歳以上ですか？</p>
<a href="/index.php?adc=1&amp;from=age">はい（アダルトへ）</a>
<a href="/theater/index.php">いいえ（MGSシアターへ）</a>
</div></body></html>
"""


class FakeClient:
    """按 URL 返回预置页面，记录请求顺序。"""

    def __init__(self, pages: dict[str, str | None]):
        self.pages = pages
        self.calls: list[str] = []

    async def get_text(self, url, **kwargs):
        self.calls.append(url)
        for pattern, page in self.pages.items():
            if pattern in url:
                return (page, "" if page else "404 not found")
        return None, "unexpected url"


async def test_fetch_search_auto_confirms_age_gate():
    """命中年龄认证页时自动选「はい（アダルトへ）」再取一次（用户要求）"""
    product_html = '<html><body><div id="center_column"><div><h1>黒倒女医</h1></div></body></html>'
    client = FakeClient({"adc=1": product_html, "product_detail": AGE_GATE_HTML})
    crawler, ctx = _crawler_and_ctx("ABF-389", client=client)

    text, error = await crawler._fetch_search(ctx, "https://www.mgstage.com/product/product_detail/ABF-389/")

    assert text == product_html
    assert error == ""
    assert client.calls == [
        "https://www.mgstage.com/product/product_detail/ABF-389/",
        "https://www.mgstage.com/index.php?adc=1&from=age",
    ]


async def test_fetch_search_passes_through_when_not_age_gate():
    """正常页面只请求一次，不额外打扰站点"""
    product_html = "<html><body>ok</body></html>"
    client = FakeClient({"product_detail": product_html})
    crawler, ctx = _crawler_and_ctx("ABF-389", client=client)

    text, _ = await crawler._fetch_search(ctx, "https://www.mgstage.com/product/product_detail/ABF-389/")

    assert text == product_html
    assert len(client.calls) == 1


async def test_fetch_detail_auto_confirms_age_gate():
    """详情页同样走年龄认证兜底（首页以外的路径也要覆盖）"""
    detail_html = "<html><body>detail</body></html>"
    client = FakeClient({"adc=1": detail_html, "product_detail": AGE_GATE_HTML})
    crawler, ctx = _crawler_and_ctx("ABF-389", client=client)

    text, _ = await crawler._fetch_detail(ctx, "https://www.mgstage.com/product/product_detail/ABF-389/")

    assert text == detail_html
    assert len(client.calls) == 2


async def test_fetch_search_keeps_age_gate_page_when_no_adult_link():
    """年龄认证页上没有「はい」链接时保留原页，交给 _parse_search_page 点名"""
    client = FakeClient({"product_detail": "<html><body>年齢認証</body></html>"})
    crawler, ctx = _crawler_and_ctx("ABF-389", client=client)

    text, error = await crawler._fetch_search(ctx, "https://www.mgstage.com/product/product_detail/ABF-389/")

    assert "年齢認証" in text
    assert error == ""
    assert len(client.calls) == 1


async def test_fetch_search_falls_back_to_age_gate_page_when_confirm_fails():
    """确认页请求失败时保留原页与原始错误，不能把异常页吞掉"""
    client = FakeClient({"adc=1": None, "product_detail": AGE_GATE_HTML})
    crawler, ctx = _crawler_and_ctx("ABF-389", client=client)

    text, error = await crawler._fetch_search(ctx, "https://www.mgstage.com/product/product_detail/ABF-389/")

    assert text == AGE_GATE_HTML
    assert error == "404 not found"


async def test_get_cookies_sends_adc_like_real_scrape():
    """网络检测直连探测走 _get_cookies；不带 adc 会拿到年龄确认页而误报未解析到结果"""
    crawler, ctx = _crawler_and_ctx()
    assert crawler._get_cookies(ctx) == {"adc": "1"}


async def test_probe_number_points_at_live_product_page():
    """探测番号必须是站点真实收录的详情页番号，否则探测永远失败"""
    assert MgstageCrawler.probe_number == "ABF-389"


async def test_probe_number_search_url_shape():
    """探测番号拼出的 URL 就是用户实测能解析成功的详情页地址"""
    crawler, ctx = _crawler_and_ctx("ABF-389")
    assert await crawler._generate_search_url(ctx) == ["https://www.mgstage.com/product/product_detail/ABF-389/"]


async def test_parse_search_page_names_cloudfront_geo_block():
    """CloudFront 国家封锁页（本机非日本 IP 实测返回）必须点名，不能报「未解析到结果」"""
    html = """
    <html><head><title>Error 403</title></head><body>
    <h1>ERROR: The request could not be satisfied</h1>
    <p>The Amazon CloudFront distribution is configured to block access from your country.</p>
    <p>Request blocked. Generated by cloudfront</p>
    </body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    with pytest.raises(CrawlerException, match="CloudFront"):
        await crawler._parse_search_page(ctx, Selector(text=html), "u")


async def test_parse_search_page_names_age_gate():
    """adc 失效时的年龄确认页必须点名"""
    html = """
    <html><head><title>年齢確認</title></head><body>
    <p>18歳以上であることを確認してください / Age Verification</p>
    </body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    with pytest.raises(CrawlerException, match="年龄确认页"):
        await crawler._parse_search_page(ctx, Selector(text=html), "u")


async def test_parse_search_page_names_404():
    """番号不存在/下架页必须点名（避免按瞬时故障白等 30s+45s）"""
    html = """
    <html><head><title>404 Not Found</title></head><body>
    <p>お探しのページは見つかりませんでした</p>
    </body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    with pytest.raises(CrawlerException, match="404"):
        await crawler._parse_search_page(ctx, Selector(text=html), "u")


async def test_parse_search_page_returns_url_for_real_product_page():
    """正常商品页不受上述特征检测影响"""
    html = """
    <html><body><div id="center_column"><div><h1>サンプル商品名</h1></div>
    <table><tr><th>品番：</th><td><a>259LUXU-1111</a></td></tr></table>
    </div></body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    assert await crawler._parse_search_page(ctx, Selector(text=html), "u") == ["u"]


async def test_parse_search_page_returns_none_for_unrelated_page():
    """既非已知拦截页也无番号时，仍按原语义返回 None 走下一个候选番号"""
    crawler, ctx = _crawler_and_ctx()
    assert await crawler._parse_search_page(ctx, Selector(text="<html><body><h1>noop</h1></body></html>"), "u") is None
