"""MGStage 探测间歇失败回归。

用户实测：`mgstage 200 609 ms 代理 探测失败: 搜索失败: 搜索页未解析到结果`，
且「有时候正常，但经常出现」。根因是站点侧软性拦截返回 200 非商品页，旧版一律
归为「未解析到结果」，用户无从判断是地域封锁、年龄确认页还是番号已下架。
这里锁定两类行为：`_get_cookies` 带 adc（探测与真实刮削一致），
以及「假 200」页面必须点名。
"""

import pytest
from parsel import Selector

from mdcx.crawlers.base import CrawlerException
from mdcx.crawlers.mgstage import MgstageCrawler
from mdcx.models.model_types import CrawlerInput

pytestmark = pytest.mark.asyncio


def _crawler_and_ctx():
    crawler = MgstageCrawler(client=None, browser=None)
    inp = CrawlerInput.empty()
    inp.number = "259LUXU-1111"
    return crawler, crawler.new_context(inp)


async def test_get_cookies_sends_adc_like_real_scrape():
    """网络检测直连探测走 _get_cookies；不带 adc 会拿到年龄确认页而误报未解析到结果"""
    crawler, ctx = _crawler_and_ctx()
    assert crawler._get_cookies(ctx) == {"adc": "1"}


async def test_probe_number_still_recorded():
    """探测番号 259LUXU-1111 用户实测收录，勿随意更换"""
    assert MgstageCrawler.probe_number == "259LUXU-1111"


async def test_parse_search_page_names_cloudfront_geo_block():
    """CloudFront 国家封锁页（本机非日本 IP 实测返回）必须点名，不能报「未解析到结果」"""
    html = """
    <html><head><title>Error 403</title></head><body>
    <h1>ERROR: The request could not be satisfied</h1>
    <p>The Amazon CloudFront distribution is configured to block access from your country.</p>
    <p>Request blocked. Generated by cloudfront</p>
    </body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    with pytest.raises(CrawlerException, match="CloudFront"):
        await crawler._parse_search_page(ctx, Selector(text=html), "u")


async def test_parse_search_page_names_age_gate():
    """adc 失效时的年龄确认页必须点名"""
    html = """
    <html><head><title>年齢確認</title></head><body>
    <p>18歳以上であることを確認してください / Age Verification</p>
    </body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    with pytest.raises(CrawlerException, match="年龄确认页"):
        await crawler._parse_search_page(ctx, Selector(text=html), "u")


async def test_parse_search_page_names_404():
    """番号不存在/下架页必须点名（避免按瞬时故障白等 30s+45s）"""
    html = """
    <html><head><title>404 Not Found</title></head><body>
    <p>お探しのページは見つかりませんでした</p>
    </body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    with pytest.raises(CrawlerException, match="404"):
        await crawler._parse_search_page(ctx, Selector(text=html), "u")


async def test_parse_search_page_returns_url_for_real_product_page():
    """正常商品页不受上述特征检测影响"""
    html = """
    <html><body><div id="center_column"><div><h1>サンプル商品名</h1></div>
    <table><tr><th>品番：</th><td><a>259LUXU-1111</a></td></tr></table>
    </div></body></html>
    """

    crawler, ctx = _crawler_and_ctx()
    assert await crawler._parse_search_page(ctx, Selector(text=html), "u") == ["u"]


async def test_parse_search_page_returns_none_for_unrelated_page():
    """既非已知拦截页也无番号时，仍按原语义返回 None 走下一个候选番号"""
    crawler, ctx = _crawler_and_ctx()
    assert await crawler._parse_search_page(ctx, Selector(text="<html><body><h1>noop</h1></body></html>"), "u") is None
